import { Instrument_Sans } from "next/font/google";
import "./globals.css";

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "offset® — studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {
  return (
    <html
      lang="en"
      className={`${instrumentSans.variable} h-full antialiased noise`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        {modal}
      </body>
    </html>
  );
}
